version: '3.8'

services:
  api:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - hotlabel-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hotlabel_qa
    ports:
      - "5434:5432"
    networks:
      - hotlabel-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - hotlabel-network

networks:
  hotlabel-network:
    name: hotlabel
    external: true

volumes:
  postgres_data:
