version: '3.8'

services:
  # Quality Assurance Service configured for HotLabel Infrastructure
  qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotlabel-qa
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hotlabel_qa
      - REDIS_URL=redis://redis:6379/2
      - API_V1_STR=/api/v1
      - SERVICE_NAME=quality-assurance
      - TASK_SERVICE_URL=http://tasks:8000/api/v1
      - USER_SERVICE_URL=http://users:8000/api/v1
      - SECRET_KEY=your-secure-key-here
      - HIGH_CONFIDENCE_THRESHOLD=0.85
      - MEDIUM_CONFIDENCE_THRESHOLD=0.60
      - GOLDEN_SET_PERCENTAGE=0.10
      - CONSENSUS_REQUIRED_AGREEMENT=0.75
      - MINIMUM_CONSENSUS_VALIDATORS=3
    networks:
      - hotlabel-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres
      - redis

  # Reference to external services (these won't be created but help with dependencies)
  postgres:
    image: postgres:15
    container_name: hotlabel-postgres
    networks:
      - hotlabel-network
    restart: "no"
    deploy:
      replicas: 0
    
  redis:
    image: redis:7
    container_name: hotlabel-redis
    networks:
      - hotlabel-network
    restart: "no"
    deploy:
      replicas: 0

networks:
  hotlabel-network:
    external: true
    name: hotlabel-network